# Generated by Django 3.2.7 on 2021-11-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
